<a href="https://colab.research.google.com/github/Shadhin-f/Machine-Learning/blob/main/data_preprocessing_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Template

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## Importing the dataset

In [ ]:
dataset = pd.read_csv('data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Italy' 'Male' 'Bachelor' 41.0 68000.0 720.0]
 ['Portugal' 'Female' 'Master' 33.0 49000.0 680.0]
 ['Netherlands' 'Male' 'PhD' 29.0 52000.0 700.0]
 ['Portugal' 'Female' 'Bachelor' 45.0 nan nan]
 ['Italy' 'Female' 'High School' 38.0 57000.0 750.0]
 ['Netherlands' 'Male' 'Bachelor' nan 61000.0 690.0]
 ['Portugal' 'Female' 'Master' 36.0 55000.0 730.0]
 ['Italy' 'Male' 'PhD' 44.0 72000.0 710.0]
 ['Netherlands' 'Female' 'Bachelor' 47.0 81000.0 nan]
 ['Portugal' 'Male' 'Master' 39.0 nan 700.0]]


In [ ]:
print(y)

['Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes']


# Missing data

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:,3:6])
x[:,3:6] = imputer.transform(x[:,3:6])

In [ ]:
print(x)

[['Italy' 'Male' 'Bachelor' 41.0 68000.0 720.0]
 ['Portugal' 'Female' 'Master' 33.0 49000.0 680.0]
 ['Netherlands' 'Male' 'PhD' 29.0 52000.0 700.0]
 ['Portugal' 'Female' 'Bachelor' 45.0 61875.0 710.0]
 ['Italy' 'Female' 'High School' 38.0 57000.0 750.0]
 ['Netherlands' 'Male' 'Bachelor' 39.111111111111114 61000.0 690.0]
 ['Portugal' 'Female' 'Master' 36.0 55000.0 730.0]
 ['Italy' 'Male' 'PhD' 44.0 72000.0 710.0]
 ['Netherlands' 'Female' 'Bachelor' 47.0 81000.0 710.0]
 ['Portugal' 'Male' 'Master' 39.0 61875.0 700.0]]


# Ecoding Categories

## HotEncoding

In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0, 1, 2])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 41.0 68000.0 720.0]
 [0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 33.0 49000.0 680.0]
 [0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 29.0 52000.0 700.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 45.0 61875.0 710.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 38.0 57000.0 750.0]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 39.111111111111114 61000.0 690.0]
 [0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 36.0 55000.0 730.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 44.0 72000.0 710.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 47.0 81000.0 710.0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 39.0 61875.0 700.0]]


## LabelEncoding


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 0 1 0 1 0 1 0 1 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [ ]:
print(x_train)

[[0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 36.0 55000.0 730.0]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 38.0 57000.0 750.0]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 41.0 68000.0 720.0]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 45.0 61875.0 710.0]
 [0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 33.0 49000.0 680.0]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 44.0 72000.0 710.0]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 47.0 81000.0 710.0]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 39.111111111111114 61000.0 690.0]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 29.0 52000.0 700.0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 39.0 61875.0 700.0]]


In [ ]:
print(y_train)

[1 1 1 0 0 0 1 0]


In [ ]:
print(y_test)

[1 1]


# Feature Scaling

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 9:] = sc.fit_transform(x_train[:, 9:])
x_test[:, 9:] = sc.transform(x_test[:, 9:])

In [ ]:
print(x_train)

[[0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 -0.9826752396615952
  -0.8482487309872695 0.8551861104941366]
 [1.0 0.0 0.0 1.0 0.0 0.0 1.0 0.0 0.0 -0.5348738646259316
  -0.6390467318227792 1.8325416653445785]
 [1.0 0.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 0.1368281979275638
  0.5115642635819179 0.3665083330689157]
 [0.0 0.0 1.0 1.0 0.0 1.0 0.0 0.0 0.0 1.032430947998891
  -0.12911685885933394 -0.12216944435630527]
 [0.0 0.0 1.0 1.0 0.0 0.0 0.0 1.0 0.0 -1.6543773022150907
  -1.4758547284807406 -1.588202776631968]
 [1.0 0.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 0.8085302604810592
  0.9299682619108985 -0.12216944435630527]
 [0.0 1.0 0.0 1.0 0.0 1.0 0.0 0.0 0.0 1.4802323230345544
  1.8713772581511052 -0.12216944435630527]
 [0.0 1.0 0.0 0.0 1.0 1.0 0.0 0.0 0.0 -0.2860953229394511
  -0.22064273349379845 -1.099524999206747]]


In [ ]:
print(x_test)

[[0.0 1.0 0.0 0.0 1.0 0.0 0.0 0.0 1.0 29.0 52000.00000000001 700.0]
 [0.0 0.0 1.0 0.0 1.0 0.0 0.0 1.0 0.0 39.0 61875.00000000001 700.0]]
